test = {'TIENE_RAIZ': 1, 'PALABRA_LARGO': 2, u'PALABRA_am': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0, u'CAT_SINTACTICA_VBP': 1}
lala = {0: {'feature': {'TIENE_RAIZ': 0, 'PALABRA_LARGO': 4, u'PALABRA_Will': 1, 'FULL_MINUSCULAS': 0, u'CAT_SINTACTICA_MD': 1, 'FULL_MAYUSCULAS': 0, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 1}, 'cuenta': 1}, 1: {'feature': {'TIENE_RAIZ': 0, 'PALABRA_LARGO': 6, u'CAT_SINTACTICA_NN': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0, u'PALABRA_sulfur': 1}, 'cuenta': 1}, 2: {'feature': {'TIENE_RAIZ': 0, 'PALABRA_LARGO': 6, u'CAT_SINTACTICA_NN': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, u'PALABRA_damage': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0}, 'cuenta': 1}, 3: {'feature': {'TIENE_RAIZ': 0, 'PALABRA_LARGO': 6, u'CAT_SINTACTICA_NN': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, u'PALABRA_guitar': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0}, 'cuenta': 1}, 4: {'feature': {'TIENE_RAIZ': 1, 'PALABRA_LARGO': 7, u'CAT_SINTACTICA_NNS': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, u'PALABRA_strings': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0}, 'cuenta': 1}, 5: {'feature': {'TIENE_RAIZ': 0, 'PALABRA_LARGO': 1, u'PALABRA_?': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 0, u'CAT_SINTACTICA_.': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0}, 'cuenta': 1}, 6: {'feature': {'TIENE_RAIZ': 1, 'PALABRA_LARGO': 2, u'PALABRA_am': 1, 'FULL_MAYUSCULAS': 0, 'FULL_MINUSCULAS': 1, 'INICIO__MAYUSCULAS_RESTO_MINUSCULAS': 0, u'CAT_SINTACTICA_VBP': 1}, 'cuenta': 1}}


for la in lala:
  if lala[la]['feature'] == test:
    print "iguales"
  else:
    print "no son iguales"

print set(test).issubset(set(lala))